## 쿼리문 파일

# todo 등록
INSERT_TODO = "INSERT INTO TODOS(TEXT, STRT_DATE, END_DATE, UPT_DATE, STATUS)VALUES(%s, %s, NULL, %s, 'N')"

# todo list 조회
SELECT_TODO_LIST = "SELECT ID, TEXT, STRT_DATE, END_DATE, UPT_DATE, STATUS FROM TODOS WHERE UPT_DATE >= %s OR STATUS <> 'C'"

# todo 수정
UPDATE_TODO = "UPDATE TODOS SET STATUS = CASE WHEN STATUS = 'C' THEN 'N' ELSE 'C' END, UPT_DATE = %s WHERE ID = %s"
