## 쿼리문 파일

# todo 등록
INSERT_TODO = "INSERT INTO TODOS(TEXT, STRT_DATE, END_DATE, UPT_DATE, STATUS)VALUES(%s, %s, NULL, %s, 'N')"

# todo list 조회
SELECT_TODO_LIST = "SELECT ID, TEXT, STRT_DATE, END_DATE, UPT_DATE, STATUS FROM TODOS WHERE UPT_DATE >= %s OR STATUS <> 'C'"

# 해당 날짜 완료된 todo list 조회
SELECT_HISTORY_TODO_LIST = "SELECT ID, TEXT, STRT_DATE, END_DATE, UPT_DATE, STATUS FROM TODOS WHERE UPT_DATE = %s AND STATUS = 'C'"

# todo 완료처리
UPDATE_STATUS = "UPDATE TODOS SET STATUS = CASE WHEN STATUS = 'C' THEN 'N' ELSE 'C' END, UPT_DATE = %s WHERE ID = %s"

# todo 수정
UPDATE_TODO = "UPDATE TODOS SET TEXT = %s, UPT_DATE = %s WHERE ID = %s"

# todo 삭제
DELETE_TODO = "DELETE FROM TODOS WHERE ID = %s"
